services:
  - type: web
    name: medusa-backend
    env: node
    plan: free
    buildCommand: corepack enable && yarn install && yarn build && yarn medusa db:migrate && yarn medusa build
    startCommand: medusa start --skip-seed
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusa-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: BACKEND_URL
        value: https://your-app-name.onrender.com
      - key: STOREFRONT_URL
        value: https://your-storefront-url.com
      - key: STORE_CORS
        value: https://your-storefront-url.com
      - key: ADMIN_CORS
        value: https://your-admin-url.com
      - key: AUTH_CORS
        value: https://your-storefront-url.com
      - key: DISABLE_ADMIN
        value: false

databases:
  - name: medusa-postgres
    databaseName: medusa
    user: medusa
    plan: free

services:
  - type: redis
    name: medusa-redis
    plan: free 