services:
  - type: web
    name: medusa-backend
    env: node
    plan: free
    buildCommand: corepack enable && yarn install && yarn build && yarn medusa db:migrate --skip-seed && yarn medusa build
    startCommand: medusa start --skip-seed
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusa-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: BACKEND_URL
        value: https://your-app-name.onrender.com
      - key: STOREFRONT_URL
        value: https://your-storefront-url.com
      - key: STORE_CORS
        value: https://your-storefront-url.com
      - key: ADMIN_CORS
        value: https://your-admin-url.com
      - key: AUTH_CORS
        value: https://your-storefront-url.com
      - key: S3_FILE_URL
        value: https://caf2520911d2089f7451d31c9bd5ec6d.r2.cloudflarestorage.com/rosti
      - key: S3_ACCESS_KEY_ID
        value: 2410420ad1d40abff4d72ffd90d4896a
      - key: S3_SECRET_ACCESS_KEY
        value: f9132a39c48fcd4affda2dea1532ef88bf2cc2792c1a6f32546904aba13e381
      - key: S3_REGION
        value: auto
      - key: S3_BUCKET
        value: rosti
      - key: S3_ENDPOINT
        value: https://caf2520911d2089f7451d31c9bd5ec6d.r2.cloudflarestorage.com

databases:
  - name: medusa-postgres
    databaseName: medusa
    user: medusa
    plan: free

services:
  - type: redis
    name: medusa-redis
    plan: free 